-- MySQL Script generated by MySQL Workbench
-- Wed 15 Nov 2017 03:32:09 PM UTC
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema upperLimit
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema upperLimit
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `upperLimit` DEFAULT CHARACTER SET utf8 ;
USE `upperLimit` ;

-- -----------------------------------------------------
-- Table `upperLimit`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `upperLimit`.`Employee` (
  `employeeId` INT(11) NOT NULL,
  `Name` VARCHAR(700) NOT NULL,
  `addressLine1` VARCHAR(45) NOT NULL,
  `picture` LONGBLOB NULL,
  `addressLine2` VARCHAR(45) NULL DEFAULT NULL,
  `phoneNumber1` VARCHAR(45) NOT NULL,
  `phoneNumber2` VARCHAR(45) NULL DEFAULT NULL,
  `email_address` VARCHAR(45) NOT NULL,
  `password` VARCHAR(15) NOT NULL,
  `isManager` TINYINT NULL,
  PRIMARY KEY (`employeeId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `upperLimit`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `upperLimit`.`Client` (
  `clientId` INT(11) NOT NULL AUTO_INCREMENT,
  `employeeId` INT(11) NOT NULL,
  `name` VARCHAR(700) NOT NULL,
  `picture` LONGBLOB NULL,
  `addressLine1` VARCHAR(45) NOT NULL,
  `addressLine2` VARCHAR(45) NULL DEFAULT NULL,
  `province` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `postalCode` VARCHAR(20) NULL DEFAULT NULL,
  `phoneNumber1` VARCHAR(15) NOT NULL,
  `phoneNumber2` VARCHAR(15) NULL DEFAULT NULL,
  PRIMARY KEY (`clientId`),
  INDEX `fk_Client_Agent_idx` (`employeeId` ASC),
  CONSTRAINT `fk_Client_Agent`
    FOREIGN KEY (`employeeId`)
    REFERENCES `upperLimit`.`Employee` (`employeeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `upperLimit`.`CarInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `upperLimit`.`CarInfo` (
  `carId` INT(11) NOT NULL AUTO_INCREMENT,
  `clientId` INT(11) NOT NULL,
  `manufacturer` VARCHAR(45) NOT NULL,
  `modelYear` VARCHAR(45) NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `value` DECIMAL(15,5) NOT NULL,
  `picture1` LONGBLOB NULL,
  `picture2` LONGBLOB NULL,
  PRIMARY KEY (`carId`),
  INDEX `fk_CarInfo_Client1_idx` (`clientId` ASC),
  CONSTRAINT `fk_CarInfo_Client1`
    FOREIGN KEY (`clientId`)
    REFERENCES `upperLimit`.`Client` (`clientId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `upperLimit`.`Notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `upperLimit`.`Notification` (
  `notifId` INT NOT NULL,
  `employeeId` INT NOT NULL,
  `message` VARCHAR(100) NOT NULL,
  `isRead` TINYINT NOT NULL,
  `timeCreated` DATETIME NOT NULL,
  PRIMARY KEY (`notifId`),
  INDEX `employeeId_idx` (`employeeId` ASC),
  CONSTRAINT `employeeId`
    FOREIGN KEY (`employeeId`)
    REFERENCES `upperLimit`.`Employee` (`employeeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
